ALTER TABLE "Lead" ADD COLUMN "companyName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "contactName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "discordUsername" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "telegram" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "otherContact" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "website" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "discordInvite" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "scannerResultId" TEXT REFERENCES "ScannerResult"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "ScannerState" ("id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',"status" TEXT NOT NULL DEFAULT 'IDLE',"stopRequested" BOOLEAN NOT NULL DEFAULT false,"currentResultId" TEXT,"startedAt" DATETIME,"stoppedAt" DATETIME,"updatedAt" DATETIME NOT NULL);
CREATE TABLE "ScannerResult" ("id" TEXT NOT NULL PRIMARY KEY,"url" TEXT NOT NULL,"normalizedUrl" TEXT NOT NULL,"title" TEXT NOT NULL DEFAULT '',"domainId" TEXT NOT NULL,"scanStatus" TEXT NOT NULL DEFAULT 'Pending',"httpStatus" INTEGER,"scanDuration" INTEGER,"error" TEXT,"scannedAt" DATETIME,"firstSeen" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastSeen" DATETIME NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "ScannerResult_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "ScannerSource" ("id" TEXT NOT NULL PRIMARY KEY,"scannerResultId" TEXT NOT NULL,"searchSessionId" TEXT NOT NULL,"query" TEXT NOT NULL,"position" INTEGER NOT NULL,"discoveredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ScannerSource_scannerResultId_fkey" FOREIGN KEY ("scannerResultId") REFERENCES "ScannerResult"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ScannerSource_searchSessionId_fkey" FOREIGN KEY ("searchSessionId") REFERENCES "SearchSession"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "ScannerDiscordLink" ("id" TEXT NOT NULL PRIMARY KEY,"scannerResultId" TEXT NOT NULL,"url" TEXT NOT NULL,"inviteCode" TEXT NOT NULL,"sourcePage" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ScannerDiscordLink_scannerResultId_fkey" FOREIGN KEY ("scannerResultId") REFERENCES "ScannerResult"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Tag" ("id" TEXT NOT NULL PRIMARY KEY,"name" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "LeadTag" ("leadId" TEXT NOT NULL,"tagId" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("leadId","tagId"),CONSTRAINT "LeadTag_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "LeadTag_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ScannerResult_normalizedUrl_key" ON "ScannerResult"("normalizedUrl");
CREATE INDEX "ScannerResult_scanStatus_idx" ON "ScannerResult"("scanStatus");
CREATE UNIQUE INDEX "ScannerSource_scannerResultId_searchSessionId_key" ON "ScannerSource"("scannerResultId","searchSessionId");
CREATE UNIQUE INDEX "ScannerDiscordLink_scannerResultId_url_key" ON "ScannerDiscordLink"("scannerResultId","url");
CREATE UNIQUE INDEX "Tag_name_key" ON "Tag"("name");
CREATE INDEX "Lead_scannerResultId_idx" ON "Lead"("scannerResultId");
INSERT INTO "ScannerState" ("id","status","stopRequested","updatedAt") VALUES ('default','IDLE',false,CURRENT_TIMESTAMP);
